### ISSUE TITLE
1.18 Support

### ISSUE THREAD

**Issue by JoshuaVandaele** [VideoGameSmash12/HotbarsPlus#14]
![https://folfy.blue/sharex/uN1Zepm6vH.png](https://folfy.blue/sharex/uN1Zepm6vH.png)

**Comment by VideoGameSmash12** [comment]
I'm working on overhauling Hotbars+ as a whole to enable multi-version support. It's gonna take some time, but the end result will be great.

**Comment by VideoGameSmash12** [comment]
Done in v2, which is estimated to be complete by the end of the month.

**Comment by VideoGameSmash12** [comment]
Bit late, but the first prerelease of Hotbars+ v2 has been released, which currently supports 1.14.4 to 1.18.2.
