### ISSUE TITLE
question

### ISSUE THREAD

**Issue by a-a3458** [VideoGameSmash12/HotbarsPlus#18]
will the mod be updated to 1.19 or 1.19.1?

**Comment by VideoGameSmash12** [comment]
I'm not too sure yet. 1.19 changed how the game's text works in a way that broke the mod, and I have yet to figure out a solution that wouldn't break compatibility with earlier versions of Minecraft.

**Comment by VideoGameSmash12** [comment]
The answer is now yes. I have since added 1.19+ support in the v2 branch.
