### ISSUE TITLE
[Enhancement] Shulker box preview

### ISSUE THREAD

**Issue by a-a3458** [VideoGameSmash12/HotbarsPlus#4]
Basically, if you have it on you can see the contents of shulker boxes in your inv

**Comment by FolfyBlue** [comment]
That's, uh, a bit out of scope, but here's a mod that does that:
https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip

**Comment by VideoGameSmash12** [comment]
Agreed with @FolfyBlue: this is a bit out of scope.
