### ISSUE TITLE
Make distinction between Fabric Loader and Fabric API

### ISSUE THREAD

**Issue by ghost** [VideoGameSmash12/HotbarsPlus#8]
in a discussion thread about this mod, you claimed the minimum Fabric version is v0.11.2, which is true, but the GitHub only states the minimum version of Fabric API is v0.31.0. that is also true.

Fabric loader != Fabric API but this may not be clear to everyone.

i recommend adding the minimum Fabric loader version to the readme, and adding the Fabric API version to any discussion threads about the mod.

**Comment by VideoGameSmash12** [comment]
Planned in v2 as I rewrite the documentation.

**Comment by VideoGameSmash12** [comment]
Done.
