### ISSUE TITLE
[Enhancement] User-friendly timestamps

### ISSUE THREAD

**Issue by ghost** [VideoGameSmash12/HotbarsPlus#9]
most people cannot meaningfully interpret UNIX timestamps. to improve the user-friendliness of backups, i recommend switching to some form or variant of ISO 8601, i.e.

`yyyy-MM-dd  `at` HH:mm:ss a` -----> `2022-05-21 at 05:30:27 AM`

**Comment by VideoGameSmash12** [comment]
Good idea! I had intended to use Unix timestamps so that it would be easier to process with a "backup manager", but this might actually be better for people who don't want to use a fancy backup manager and just want to manage their backups on their own.

**Comment by VideoGameSmash12** [comment]
Done in v2
